{{- if .Values.reconciliationWorker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rfq-market-maker.fullname" . }}-reconciliation-worker
  annotations:
    {{- with .Values.reconciliationWorker.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  selector:
    {{- include "rfq-market-maker.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: reconciliation-worker
  ports:
    - name: http
      port: {{ .Values.reconciliationWorker.port }}
      targetPort: http
{{- end }}
