apiVersion: v1
kind: Service
metadata:
  name: rfq-analytics-worker
  namespace: rfq-market-maker
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "3002"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rfq-analytics-worker
  ports:
    - name: http
      port: 3002
      targetPort: http
