apiVersion: v1
kind: Service
metadata:
  name: rfq-backend
  namespace: rfq-market-maker
  labels:
    app.kubernetes.io/name: rfq-backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rfq-backend
  ports:
    - name: http
      port: 3000
      targetPort: http
