apiVersion: v1
kind: Secret
metadata:
  name: rfq-database-migration-secrets
  namespace: rfq-market-maker
type: Opaque
stringData:
  DATABASE_URL: postgres://rfq-migrator:replace-with-password@postgres.example.com:5432/rfq_market_maker
