apiVersion: v1
kind: Secret
metadata:
  name: rfq-frontend-api-key
  namespace: rfq-market-maker
type: Opaque
stringData:
  api-key.conf: |
    proxy_set_header X-API-Key "replace-with-key-id.replace-with-32-character-minimum-secret";
