apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rfq-reconciliation-worker
  namespace: rfq-market-maker
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rfq-reconciliation-worker
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 3003
  egress:
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 5432
