apiVersion: v1
kind: Service
metadata:
  name: rfq-settlement-indexer
  namespace: rfq-market-maker
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "3004"
spec:
  selector:
    app.kubernetes.io/name: rfq-settlement-indexer
  ports:
    - name: http
      port: 3004
      targetPort: http
