apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rfq-signer-default
  namespace: rfq-market-maker
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rfq-signer
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: rfq-backend
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: 3006
  egress: []
