apiVersion: v1
kind: Service
metadata:
  name: rfq-toxic-flow-analyzer
  namespace: rfq-market-maker
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "3005"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: rfq-toxic-flow-analyzer
  ports:
    - name: http
      port: 3005
      targetPort: http
